# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dc6216221b79d1b93cbb697fa4e21455733be20b78bb290f8aa8d361a329fbdc5f74755f2cfad4c2a47d5126a95b2410c2b027c0347779f289385f1f599c77c

test:
  secret_key_base: 79429de64bc0630cf9cbf626ee292342e103d23229610c1cb261db12117daea161998289c4aee901a6da962dd3a22e4c6fe18ba6c458355bacd4d52e013ae20a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
